<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jpfaq_comments"
 *
 * Auto generated by Extension Builder 2014-01-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'jpFAQ Comments',
	'description' => 'Extended version of the jpfaq extension with comments per question.',
	'category' => 'plugin',
	'author' => 'Matthias Toews',
	'author_email' => 'm.toews@comnerds.com',
	'author_company' => 'comnerds.com',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>